### PR TITLE
edited sql

### PR DESCRIPTION
**Pull request by axcooper**
## Pull request overview

Amended sql code for characteristics

## Pull request checklist

Please check if your PR fulfills the following:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Tests have been run locally and are passing (`shinytest2::test_app()`)
- [x] Code is styled according to tidyverse styling (checked locally with `styler::style_dir()` and `lintr::lint_dir()`)

## What is the new behaviour?

SQL for characteristics changed so:

- zeros are now 'low'
-overall totals for each provider in
- national 'Total' is now 'Total (all providers) to be consistent with NPS tab

### CODE REVIEW

**Comment by cjrace** [comment]
Need to run the SQL query manually and save a CSV from the output, and then use the `R/data-prep/create_data_files.R` script to create new .parquet data files for the app to use

**Review by cjrace — APPROVED** [review]
Tests are failing - but don't think that happy to leave those and pick up on another branch once all the initial content is in

**Comment by axcooper** [comment]
Reviewed conflicts

**Comment by axcooper** [comment]
Reviewed conflicts

**Pull request merged**
