### PR TITLE
Fix automated tests builds

### LINKED ISSUE #25: Page 3: Create parquet file specific to subjects and standards
The main apps data file is massive, and is probably worth looking at whether a cut down version could be made for use in the subjects and standards tab

### LINKED ISSUE #43: Add basic test coverage across whole app
## Description

We haven't yet set up automated tests for all of the functionality, once we've finished making changes we should do a keep sweep and ensure a minimum level of test coverage.

## Use case

As a developer of the app I want to be automate the QA of the app so that I can easily be reassured I've not inadvertently broken any other functionality when making changes

## Additional Context

Replaces #37 #36 #16 #15

### LINKED ISSUE #46: Page 1: Create specific parquet file for first tab
The main apps data file is massive, and is probably worth looking at whether a cut down version could be made for use in the provider breakdowns tab.

### PR DESCRIPTION
**Pull request by cjrace**
## Pull request overview

Got the tests to a passing point, adding more test coverage and also removed the need for snapshotting. Reran data updates so the unsafe metadata warning would go away.

## Pull request checklist

Please check if your PR fulfills the following:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Tests have been run locally and are passing (`shinytest2::test_app()`)
- [x] Code is styled according to tidyverse styling (checked locally with `styler::style_dir()` and `lintr::lint_dir()`)

## What is the current behaviour?

We used to use snapshot tests that would compare a lot of json output against itself, these had a lot of noise and would break everytime the data changed.

## What is the new behaviour?

We now have custom functions that check the number of rendered rows for a table or whether a plot has been created, as well as checking for errors in the console. These tests should be much more robust.

## Anything else

I've also updated the documentation a little to help make it easier to pick up.

Resolves #43 and #42.

Updating this to also resolve #46 and resolve #25 to reduce the amount of data loaded into the app (hoping that will help with the errors when running the tests).

### CODE REVIEW

**Comment by axcooper** [comment]
I don't feel very qualified to review this, but I have run shinytest2::test_app() and I am getting errors.

Caused by error in `app_start_shiny()`:
! Error starting shiny application:
Sourcing .Rprofile...
Loading required package: shiny
Running application in test mode.
Error : Out of memory: realloc of size 8388608 failed

**Comment by axcooper** [comment]
I am still getting the error:
Caused by error in `app_start_shiny()`:
! Error starting shiny application:
Sourcing .Rprofile...
Loading required package: shiny
Running application in test mode.
Error : Out of memory: realloc of size 33554432 failed

[ FAIL 3 | WARN 0 | SKIP 0 | PASS 51 ]

**Comment by cjrace** [comment]
> I am still getting the error: Caused by error in `app_start_shiny()`: ! Error starting shiny application: Sourcing .Rprofile... Loading required package: shiny Running application in test mode. Error : Out of memory: realloc of size 33554432 failed
> 
> [ FAIL 3 | WARN 0 | SKIP 0 | PASS 51 ]

That's frustrating, though seems like my changes before made some progress. One option could be to simplify the amount of automated QA we have for now and then look to add back in at a later point.

I'll put this back to draft while I do some more thinking on this and let you know!

**Review by axcooper — APPROVED** [review]
I've looked over the code, and the changes seems OK. I've run it locally, and it's quicker to load, and the tests pass.

**Pull request merged**
